# Conda environment configuration for the UNLV NPM Candida auris Project
# This file contains all software dependencies for the Amplicon, WGS, and RNA-Seq workflows.
#
# To create the environment, run:
#   conda env create -f environment.yml
#
# To activate the environment, run:
#   conda activate npm-candida
#
name: npm-candida
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # === Core Bioinformatics Tools ===
  - bwa
  - fastp
  - fgbio
  - ivar
  - samtools
  - qualimap
  - snpeff # For variant annotation (includes SnpSift)
  - snpsift
  - pigz     # Parallel gzip


  # === Workflow & Parallelization ===
  - nextflow
  - parallel # GNU Parallel

  # === Python and Core Libraries ===
  - python=3.10
  - pandas
